### PR TITLE
Minigame launch

### PR DESCRIPTION
**Pull request by roger-chau**

### CODE REVIEW

**Comment by roger-chau** [comment]
Missing two minigames, hopefully they're finished soon

**Comment by owencooke** [comment]
@roger-chau it works great! Maybe we should handle the case when minigame is "None" right now though? currently if you go to one of the other offices and try to start it, the app crashes.

**Comment by roger-chau** [comment]
Agreed. I can make it do nothing as a placeholder... I should also probably add a check condition to make sure you already talked to the doctor as well.

**Review by owencooke — APPROVED** [review]
Beautiful!

**Review by pratham124 — APPROVED** [review]

**Pull request merged**
